iconicwp/WordPress-Settings-Framework

wp-settings-framework.php
You can init the settings without passing a settings file, then simply add a filter to form the settings array.
=> Remove requirement of settings file

wp-settings-framework.php
Note: [WordPress 5.5 removes jQuery migrate 1.x](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/)
=> replace $.live with $.on to keep the compatiblity with WordPress 5.5

.gitignore, settings/example-settings.php, wp-settings-framework.php
Fix for: #62 
Add the following options to render a link either as a tool tip, or inline:
```
'link'          => esc_url( 'https://google.com' ),
'link_type'     => 'tooltip', // Can be 'tooltip' or 'link'. Default is 'tooltip'.
'link_text'     => esc_html__( 'Learn More', 'orderable' ), // Default is 'Learn More'.
'link_external' => true, // Default is `true`.
```
Video demo: https://cln.sh/jLN6XC
=> #62 - [new] Add links to titles

.gitignore, assets/js/main.js, settings/example-settings.php, wp-settings-framework.php
Fixes #61.
**To show and hide tabs:**
```
$settings['tabs'][] = array(
'id'              => 'styles',
'title'           => __( 'Styles', 'flux-checkout' ),
'tabControlGroup' => 'desktop_enabled',
// 'showIfValue'     => array( true ), // show if will hide the tab unless the value matches.
'hideIfValue'     => array( true ), // hide will show the tab unless the value matches.
);
```
On your control, be sure to set the same control name:
```
array(
'id'              => 'desktop_enabled',
'title'           => __( 'Enable on Desktop', 'flux-checkout' ),
'subtitle'        => __( 'Enable or disable Flux Checkout on Desktop.', 'flux-checkout' ),
'type'            => 'toggle',
'default'         => true,
'tabControlGroup' => 'desktop_enabled', // Needs to be set to the same tab control. Does not …
```
=> [new] Show and hide tabs and controls with control groups

assets/js/main.js
Fixes show if and hide if conditions for certain elements that are wrapped in labels.
=> [fix] Show and Hide not working if elements are wrapped in labels

wp-settings-framework.php
As reported [here](https://github.com/iconicwp/iconic-woothumbs/issues/114), PHP `8.1` fatals when the condition of a nested ternary is not parenthesized.
This PR parenthesizes all of the offending instances, as well as parenthesizing all of the ternary conditions for consistency. I've self-reviewed my changes and tested, but need a 2nd pair of 👀 to check the changes and test WooThumbs on `8.1`
Once merged, we can update deps for all products and roll out point releases next week or sooner. 🎉
=> [fix] Parenthesized conditionals in ternaries to prevent PHP 8.1 fatals.

assets/css/main.css
Add import and export fields like this:
```
'fields'              => array(
array(
'id'          => 'import',
'title'       => __( 'Import', 'jckwds' ),
'subtitle'    => __( 'Import settings', 'jckwds' ),
'type'        => 'import',
),
array(
'id'          => 'export',
'title'       => __( 'Export', 'jckwds' ),
'subtitle'    => __( 'Export settings', 'jckwds' ),
'type'        => 'export',
),
),
```
Notice that clicking on the `Export` button does not work because the hidden <input type=file> button overlaps with the export button. This PR fixes that issue. 
Video demonstrating the problem:
https://user-images.githubusercontent.com/5794565/154633935-85bb5944-011b-4c7d-a863-9ec748917ce4.mp4
=> [fix] File button overflow issue

wp-settings-framework.php
This syntax would trigger a malware warning:
```
$args['output']( $args );
```
So we replace it with 'call_user_func'. 
**Steps to Test**
1. Checkout to this branch of flux checkout: https://github.com/iconicwp/flux-checkout/pull/130. We are picking this branch because it uses the 'custom' field type of setting framework to create the swatches field.
2. Run `npm update && composer update && gulp deps`
3. Go to the Flux setting in the dashboard, ensure all fields are working fine, especially the color swatches
=> [fix] Replace () with call_user_func()

README.md, settings/example-settings.php, wp-settings-framework.php
Added support for a code editor field using WordPress's CodeMirror editor.
Supplying the 'mimetype' argument when creating the field will let you select the syntax highlighting used for the editor.
```php
array(
'id'          => 'codeeditor',
'title'       => 'Code Editor',
'desc'        => 'This is a description.',
'placeholder' => 'This is a placeholder.',
'type'        => 'codeeditor',
'mimetype'    => 'css',
'default'     => 'This is default.',
)
```
=> Add code editor field

assets/css/main.css, assets/js/main.js
@jamesckemp Based on your feedback on this PR: https://github.com/iconicwp/iconic-woo-delivery-slots/pull/234
> Can we change this slightly? I don't think we need the input field to be there transparent. it means the hover state doesn't work on the button.
Instead, could we just run jQuery( '#advance_importexport_import' ).click() when the button is clicked?
=> [update] Improve import field

assets/js/main.js
Because of the parentheses on the wpsf.on_ready function signature, it is being called immediately instead of waiting until the document is ready.
This causes some undesirable effects (such as tabs not being cached and handlers not being registered).
=> Fix wpsf being initialized before document loads

wp-settings-framework.php
Prevents the HTML (e.g. `span` tag in getting started) being escaped in the tab titles.
=> Don't escape HTML in tab titles

settings/example-settings.php, wp-settings-framework.php
The newly added `editor_settings` argument will let you pass any of [these arguments](https://developer.wordpress.org/reference/functions/wp_editor/) to the wp_editor, which is called when `editor` field is used. 
To test, edit the `editor` field in the example-settings.php, and pass in any of the above displayed arguments.
=> [update] Added new argument for the 'editor' field:- `editor_settings` to pass the custom settings arguments to wp_editor()

assets/js/main.js
While developing a feature I discovered that the Visual field does not work with the show_if/hide_if conditional logic.
This was down to the fact that the parent element of the Visual field's input is a `div`, meaning that the `Section` logic was firing.
I've updated the logic to ensure this now works as it should.
=> [fix] Show/hide logic now works for the visual field

settings/example-settings.php, wp-settings-framework.php
With this update, you can pass `multiple => true` to make the dropdown field `multiple` selectable (as shown [here](https://github.com/iconicwp/WordPress-Settings-Framework/pull/100/files#diff-83361c8ba99901a412785c2ea00da92b1a318d05afa7cf30a3e5bdd88553e6e7R141)). 
Using this we can call $('#general_general_select').select2() and create a combo box.
=> [new] Allow multiple values to be selected in dropdown

composer.json, wp-settings-framework.php
Not having an autocomplete attribute can cause the browser to fill in the password field with one saved for the current website which is not what you would want.
Also, dev tools would scream at you: https://www.chromium.org/developers/design-documents/create-amazing-password-forms/#use-autocomplete-attributes
=> add autocomplete attribute to args list

wp-settings-framework.php
Without this a settings page with only the media uploading feature does not work
=> [fix] Enqueue media script to be able to use media upload feature

assets/js/main.js
https://github.com/iconicwp/WordPress-Settings-Framework/pull/100 brought Select2 support, but this wouldn't work when adding a new row in group, as it stands right now.
It might not be best to leave the task for the framework to check each group element to see if its a select field with `multiple` set, there's no need for it to do that. It can simply fire a custom trigger every time a row is added. Then in the main plugin/theme code, we can listen for that run Select2 on the respective element:
```
$(document).on("wpsfGroupRowAdded", function () {
$(".select-multiple").each(function () { //select-multiple is class added in field setting array
if (!$(this).hasClass(".select2-hidden-accessible")) {
$(this).selectWoo();
}
});)
});
```
=> [new] Fire custom event when a group row is added

wp-settings-framework.php
When you have a new project, and no settings have been defined, multiple errors are generated.
This PR returns an empty array if `$this->settings` or `$this->settings_page` are empty, avoiding these errors.
=> Silence errors when there are no settings defined

assets/js/main.js, wp-settings-framework.php
- Expose WPSF methods for use elsewhere. ([commit](https://github.com/iconicwp/WordPress-Settings-Framework/pull/117/commits/a2608a3f26350112106de7e9a943e36e7dc89bcf))
- Ensure reindex_group logic fires for select fields. ([commit](https://github.com/iconicwp/WordPress-Settings-Framework/pull/117/commits/e28a4accf4bff590bb4e7d8b1a0c0a4fee188e97))
- Added support for custom attributes to some, but not all fields. ([commit](https://github.com/iconicwp/WordPress-Settings-Framework/pull/117/commits/39fc2f45adfc557b3edb227e7a25c43d38753827))
- Give group field table elements a unique ID for styling purposes. ([commit](https://github.com/iconicwp/WordPress-Settings-Framework/pull/117/commits/06086bb53154ec01e9f8d6cd7c4f77699d9f518a))
- Output desc field for groups, serialize group data to …
=> Several fixes and updates
